# Generated by Django 6.1 on 2026-09-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_alter_save_post'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='posts.post'),
        ),
    ]
