# Generated by Django 6.1 on 2026-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_img/user.png', null=True, upload_to='profile_img/'),
        ),
    ]
